(let ((_lookup0 (lambda (_key1 _table2) 
                  (letrec ((_loop3 (lambda (_x4) 
                                     (let ((_p32 (null? _x4))) 
                                       (if _p32 
                                           #f 
                                           (let ((_pair5 (car _x4))) 
                                             (let ((_p33 (car _pair5))) 
                                               (let ((_p34 (eq? _p33 _key1))) 
                                                 (if _p34 
                                                     _pair5 
                                                     (let ((_p35 (cdr _x4))) 
                                                       (_loop3 _p35))))))))))) 
                    (_loop3 _table2))))) 
  (let ((_properties6 '())) 
    (let ((_get7 (lambda (_key18 _key29) 
                   (let ((_x10 (_lookup0 _key18 _properties6))) 
                     (if _x10 
                         (let ((_p36 (cdr _x10))) 
                           (let ((_y11 (_lookup0 _key29 _p36))) 
                             (if _y11 
                                 (cdr _y11) 
                                 #f))) 
                         #f))))) 
      (let ((_put12 (lambda (_key113 _key214 _val15) 
                      (let ((_x16 (_lookup0 _key113 _properties6))) 
                        (if _x16 
                            (let ((_p37 (cdr _x16))) 
                              (let ((_y17 (_lookup0 _key214 _p37))) 
                                (if _y17 
                                    (set-cdr! _y17 _val15) 
                                    (let ((_p38 (cons _key214 _val15))) 
                                      (let ((_p39 (cdr _x16))) 
                                        (let ((_p40 (cons _p38 _p39))) 
                                          (set-cdr! _x16 _p40))))))) 
                            (let ((_p41 (cons _key214 _val15))) 
                              (let ((_p42 (cons _p41 '()))) 
                                (let ((_p43 (cons _key113 _p42))) 
                                  (let ((_p44 (cons _p43 _properties6))) 
                                    (set! _properties6 _p44)))))))))) 
        (let ((_dderiv18 (lambda (_a19) 
                           (let ((_p45 (pair? _a19))) 
                             (let ((_p46 (not _p45))) 
                               (if _p46 
                                   (let ((_p47 (eq? _a19 'x))) 
                                     (if _p47 
                                         1 
                                         0)) 
                                   (let ((_p48 (car _a19))) 
                                     (let ((_f20 (_get7 _p48 'dderiv))) 
                                       (if _f20 
                                           (_f20 _a19) 
                                           (error "No derivation method available")))))))))) 
          (let ((_my+dderiv21 (lambda (_a22) 
                                (let ((_p49 (cdr _a22))) 
                                  (let ((_p50 (map _dderiv18 _p49))) 
                                    (cons '+ _p50)))))) 
            (let ((_my-dderiv23 (lambda (_a24) 
                                  (let ((_p51 (cdr _a24))) 
                                    (let ((_p52 (map _dderiv18 _p51))) 
                                      (cons '- _p52)))))) 
              (let ((_*dderiv25 (lambda (_a26) 
                                  (let ((_p56 (cdr _a26))) 
                                    (let ((_p57 (map (lambda (_a27) 
                                                       (let ((_p53 (_dderiv18 _a27))) 
                                                         (let ((_p54 (cons _a27 '()))) 
                                                           (let ((_p55 (cons _p53 _p54))) 
                                                             (cons '/ _p55))))) 
                                                     _p56))) 
                                      (let ((_p58 (cons '+ _p57))) 
                                        (let ((_p59 (cons _p58 '()))) 
                                          (let ((_p60 (cons _a26 _p59))) 
                                            (cons '* _p60))))))))) 
                (let ((_/dderiv28 (lambda (_a29) 
                                    (let ((_p61 (cadr _a29))) 
                                      (let ((_p62 (_dderiv18 _p61))) 
                                        (let ((_p63 (caddr _a29))) 
                                          (let ((_p64 (cons _p63 '()))) 
                                            (let ((_p65 (cons _p62 _p64))) 
                                              (let ((_p66 (cons '/ _p65))) 
                                                (let ((_p67 (cadr _a29)))
                                                  (let ((_p68 (caddr _a29))) 
                                                    (let ((_p69 (caddr _a29))) 
                                                      (let ((_p70 (caddr _a29)))
                                                        (let ((_p71 (_dderiv18 _p70))) 
                                                          (let ((_p72 (cons _p71 '()))) 
                                                            (let ((_p73 (cons _p69 _p72))) 
                                                              (let ((_p74 (cons _p68 _p73))) 
                                                                (let ((_p75 (cons '* _p74))) 
                                                                  (let ((_p76 (cons _p75 '()))) 
                                                                    (let ((_p77 (cons _p67 _p76))) 
                                                                      (let ((_p78 (cons '/ _p77))) 
                                                                        (let ((_p79 (cons _p78 '()))) 
                                                                          (let ((_p80 (cons _p66 _p79))) 
                                                                            (cons '- _p80)))))))))))))))))))))))) (let ((_$81 (_put12 '+ 'dderiv _my+dderiv21))) (let ((_$82 (_put12 '- 'dderiv _my-dderiv23))) (let ((_$83 (_put12 '* 'dderiv _*dderiv25))) (let ((_$84 (_put12 '/ 'dderiv _/dderiv28))) (let ((_arg30 '(+ (* 3 x x) (* a x x) (* b x) 5))) (let ((_result31 '(+ (* (* 3 x x) (+ (/ 0 3) (/ 1 x) (/ 1 x))) (* (* a x x) (+ (/ 0 a) (/ 1 x) (/ 1 x))) (* (* b x) (+ (/ 0 b) (/ 1 x))) 0))) (let ((_p85 (_dderiv18 _arg30))) (equal? _p85 _result31)))))))))))))))))
