(let ((add1 (lambda (_x5) (+ 1 _x5))))
  (let ((size 5))
    (let ((mkmatrix (lambda (_rows6 _cols7)
                      (let ((_mx8 (make-vector _rows6 0)))
                        (let ((_count9 1))
                          (letrec ((__loop010 (lambda (_i11)
                                                (let ((_p43 (= _i11 _rows6)))
                                                  (if _p43
                                                      '<undefined>
                                                      (let ((_row12 (make-vector _cols7 0)))
                                                        (letrec ((__loop113 (lambda (_j14)
                                                                              (let ((_p44 (= _j14 _cols7)))
                                                                                (if _p44
                                                                                    '<undefined>
                                                                                    (let ((_$45 (vector-set! _row12 _j14 _count9)))
                                                                                      (let ((_p46 (+ _count9 1)))
                                                                                        (let ((_$47 (set! _count9 _p46)))
                                                                                          (let ((_p48 (add1 _j14)))
                                                                                            (__loop113 _p48))))))))))
                                                          (let ((_$49 (__loop113 0)))
                                                            (let ((_$50 (vector-set! _mx8 _i11 _row12)))
                                                              (let ((_p51 (add1 _i11)))
                                                                (__loop010 _p51)))))))))))
                            (let ((_$52 (__loop010 0)))
                              _mx8)))))))
      (let ((num-cols (lambda (_mx15)
                        (let ((_row16 (vector-ref _mx15 0)))
                          (vector-length _row16)))))
        (let ((mmult (lambda (_rows17 _cols18 _m119 _m220)
                       (let ((_m321 (make-vector _rows17 0)))
                         (letrec ((__loop222 (lambda (_i23)
                                               (let ((_p55 (= _i23 _rows17)))
                                                 (if _p55
                                                     '<undefined>
                                                     (let ((_m1i24 (vector-ref _m119 _i23)))
                                                       (let ((_row25 (make-vector _cols18 0)))
                                                         (letrec ((__loop326 (lambda (_j27)
                                                                               (let ((_p56 (= _j27 _cols18)))
                                                                                 (if _p56
                                                                                     '<undefined>
                                                                                     (let ((_val28 0))
                                                                                       (letrec ((__loop429 (lambda (_k30)
                                                                                                             (let ((_p57 (= _k30 _cols18)))
                                                                                                               (if _p57
                                                                                                                   '<undefined>
                                                                                                                   (let ((_p58 (vector-ref _m1i24 _k30)))
                                                                                                                     (let ((_p59 (vector-ref _m220 _k30)))
                                                                                                                       (let ((_p60 (vector-ref _p59 _j27)))
                                                                                                                         (let ((_p61 (* _p58 _p60)))
                                                                                                                           (let ((_p62 (+ _val28 _p61)))
                                                                                                                             (let ((_$63 (set! _val28 _p62)))
                                                                                                                               (let ((_p64 (add1 _k30)))
                                                                                                                                 (__loop429 _p64)))))))))))))
                                                                                         (let ((_$65 (__loop429 0)))
                                                                                           (let ((_$66 (vector-set! _row25 _j27 _val28)))
                                                                                             (let ((_p67 (add1 _j27))) (__loop326 _p67)))))))))))
                                                           (let ((_$68 (__loop326 0)))
                                                             (let ((_$69 (vector-set! _m321 _i23 _row25)))
                                                               (let ((_p70 (add1 _i23))) (__loop222 _p70))))))))))))
                           (let ((_$71 (__loop222 0)))
                             _m321))))))
          (let ((main (lambda (_n31)
                        (let ((_mm32 0))
                          (let ((_m133 (mkmatrix size size)))
                            (let ((_m234 (mkmatrix size size)))
                              (letrec ((_loop35 (lambda (_iter36)
                                                  (let ((_p73 (> _iter36 0)))
                                                    (if _p73
                                                        (let ((_p74 (mmult size size _m133 _m234)))
                                                          (let ((_$75 (set! _mm32 _p74)))
                                                            (let ((_p76 (- _iter36 1)))
                                                              (_loop35 _p76))))
                                                        '<undefined>)))))
                                (let ((_p77 (string->number _n31)))
                                  (let ((_$78 (_loop35 _p77)))
                                    (let ((_r037 (vector-ref _mm32 0)))
                                      (let ((_r238 (vector-ref _mm32 2)))
                                        (let ((_r339 (vector-ref _mm32 3)))
                                          (let ((_r440 (vector-ref _mm32 4)))
                                            (let ((_p79 (vector-ref _r037 0)))
                                              (let ((_p80 (vector-ref _r238 3)))
                                                (let ((_p81 (vector-ref _r339 2)))
                                                  (let ((_p82 (vector-ref _r440 4)))
                                                    (let ((xx1 (cons _p81 _p82)))
                                                      (let ((xx2 (cons _p80 xx1)))
                                                        (cons _p79 xx2))))))))))))))))))))
            (main "2")))))))

; > matrix 10
; 270165 1061760 1453695 1856025