;;; The Computer Language Benchmarks Game
;;; http://shootout.alioth.debian.org/
;;;
;;; contributed by Anthony Borla

(let ((main (lambda (_args1)
              (let ((_p19 (null? _args1)))
                (let ((_n2 (if _p19
                               1
                               (let ((_p20 (car _args1)))
                                 (string->number _p20)))))
                  (let ((_alt3 1))
                    (let ((_d24 0))
                      (let ((_d35 0))
                        (let ((_ds6 0))
                          (let ((_dc7 0))
                            (let ((_s08 0))
                              (let ((_s19 0))
                                (let ((_s210 0))
                                  (let ((_s311 0))
                                    (let ((_s412 0))
                                      (let ((_s513 0))
                                        (let ((_s614 0))
                                          (let ((_s715 0))
                                            (let ((_s816 0))
                                              (letrec ((__loop017 (lambda (_d18)
                                                                    (let ((_p21 (< _n2 _d18)))
                                                                      (if _p21
                                                                          '<undefined>
                                                                          (let ((_p22 (* _d18 _d18)))
                                                                            (let ((_$23 (set! _d24 _p22)))
                                                                              (let ((_p24 (* _d24 _d18)))
                                                                                (let ((_$25 (set! _d35 _p24)))
                                                                                  (let ((_p26 (sin _d18)))
                                                                                    (let ((_$27 (set! _ds6 _p26)))
                                                                                      (let ((_p28 (cos _d18)))
                                                                                        (let ((_$29 (set! _dc7 _p28)))
                                                                                          (let ((_p30 (/ 2 3)))
                                                                                            (let ((_p31 (- _d18 1)))
                                                                                              (let ((_p32 (expt _p30 _p31)))
                                                                                                (let ((_p33 (+ _s08 _p32)))
                                                                                                  (let ((_$34 (set! _s08 _p33)))
                                                                                                    (let ((_p35 (sqrt _d18)))
                                                                                                      (let ((_p36 (/ 1 _p35)))
                                                                                                        (let ((_p37 (+ _s19 _p36)))
                                                                                                          (let ((_$38 (set! _s19 _p37)))
                                                                                                            (let ((_p39 (+ _d18 1)))
                                                                                                              (let ((_p40 (* _d18 _p39)))
                                                                                                                (let ((_p41 (/ 1 _p40)))
                                                                                                                  (let ((_p42 (+ _s210 _p41)))
                                                                                                                    (let ((_$43 (set! _s210 _p42)))
                                                                                                                      (let ((_p44 (* _ds6 _ds6)))
                                                                                                                        (let ((_p45 (* _d35 _p44)))
                                                                                                                          (let ((_p46 (/ 1 _p45)))
                                                                                                                            (let ((_p47 (+ _s311 _p46)))
                                                                                                                              (let ((_$48 (set! _s311 _p47)))
                                                                                                                                (let ((_p49 (* _dc7 _dc7)))
                                                                                                                                  (let ((_p50 (* _d35 _p49)))
                                                                                                                                    (let ((_p51 (/ 1 _p50)))
                                                                                                                                      (let ((_p52 (+ _s412 _p51)))
                                                                                                                                        (let ((_$53 (set! _s412 _p52)))
                                                                                                                                          (let ((_p54 (/ 1 _d18)))
                                                                                                                                            (let ((_p55 (+ _s513 _p54)))
                                                                                                                                              (let ((_$56 (set! _s513 _p55)))
                                                                                                                                                (let ((_p57 (/ 1 _d24)))
                                                                                                                                                  (let ((_p58 (+ _s614 _p57)))
                                                                                                                                                    (let ((_$59 (set! _s614 _p58)))
                                                                                                                                                      (let ((_p60 (/ _alt3 _d18)))
                                                                                                                                                        (let ((_p61 (+ _s715 _p60)))
                                                                                                                                                          (let ((_$62 (set! _s715 _p61)))
                                                                                                                                                            (let ((_p63 (* 2 _d18)))
                                                                                                                                                              (let ((_p64 (- _p63 1)))
                                                                                                                                                                (let ((_p65 (/ _alt3 _p64)))
                                                                                                                                                                  (let ((_p66 (+ _s816 _p65)))
                                                                                                                                                                    (let ((_$67 (set! _s816 _p66)))
                                                                                                                                                                      (let ((_p68 (- _alt3)))
                                                                                                                                                                        (let ((_$69 (set! _alt3 _p68)))
                                                                                                                                                                          (let ((_p70 (+ _d18 1)))
                                                                                                                                                                            (__loop017 _p70)))))))))))))))))))))))))))))))))))))))))))))))))))))))
                                                (let ((_$71 (__loop017 1))) _s816)))))))))))))))))))))
  (let ((args '("25")))
    (main args)))