;; Expected result: "public class BOut extends RuntimeEnvironment {\n public static void main (String[] args) {\nnew IntValue(3) ;\n }\n}\n"
;; Free variables: symbol? string->symbol symbol->string pair? cons car cdr null? list? length integer? + - * = < <= number->string display string-length string-ref string-append list->string char->integer not eq? error #t #f
(let ((_cadr4 (lambda (_p5)
                (let ((_p148 (cdr _p5)))
                  (car _p148)))))
  (let ((_caadr6 (lambda (_p7)
                   (let ((_p149 (cdr _p7)))
                     (let ((_p150 (car _p149)))
                       (car _p150))))))
    (let ((_caddr8 (lambda (_p9)
                     (let ((_p151 (cdr _p9)))
                       (let ((_p152 (cdr _p151))) (car _p152))))))
      (let ((_cadddr10 (lambda (_p11)
                         (let ((_p153 (cdr _p11)))
                           (let ((_p154 (cdr _p153)))
                             (let ((_p155 (cdr _p154)))
                               (car _p155)))))))
        (letrec ((_map12 (lambda (_f13 _lst14)
                           (let ((_p156 (pair? _lst14)))
                             (if _p156
                                 (let ((_p157 (car _lst14)))
                                   (let ((_p158 (_f13 _p157)))
                                     (let ((_p159 (cdr _lst14)))
                                       (let ((_p160 (_map12 _f13 _p159)))
                                         (cons _p158 _p160)))))
                                 '())))))
          (letrec ((_append15 (lambda (_lst116 _lst217)
                                (let ((_p161 (pair? _lst116)))
                                  (let ((_p162 (not _p161)))
                                    (if _p162
                                        _lst217
                                        (let ((_p163 (car _lst116)))
                                          (let ((_p164 (cdr _lst116)))
                                            (let ((_p165 (_append15 _p164 _lst217)))
                                              (cons _p163 _p165))))))))))
            (let ((_string->list18 (lambda (_s19)
                                     (letrec ((_f20 (lambda (_i21)
                                                      (let ((_p166 (string-length _s19)))
                                                        (let ((_p167 (< _i21 _p166)))
                                                          (if _p167
                                                              (let ((_p168 (string-ref _s19 _i21)))
                                                                (let ((_p169 (+ _i21 1)))
                                                                  (let ((_p170 (_f20 _p169)))
                                                                    (cons _p168 _p170))))
                                                              '()))))))
                                       (_f20 0)))))
              (let ((_tagged-list?22
                     (lambda (_tag23 _l24)
                       (let ((_p171 (pair? _l24)))
                         (if _p171
                             (let ((_p172 (car _l24)))
                               (eq? _tag23 _p172)) #f)))))
                (let ((_char->natural25 (lambda (_c26)
                                          (let ((_i27 (char->integer _c26)))
                                            (let ((_p173 (< _i27 0)))
                                              (if _p173
                                                  (* -2 _i27)
                                                  (let ((_p174 (* 2 _i27)))
                                                    (+ _p174 1))))))))
                  (let ((_integer->char-list28 (lambda (_n29)
                                                 (let ((_p175 (number->string _n29)))
                                                   (_string->list18 _p175)))))
                    (let ((_const?30 (lambda (_exp31) (integer? _exp31))))
                      (let ((_ref?32 (lambda (_exp33) (symbol? _exp33))))
                        (let ((_let?34 (lambda (_exp35) (_tagged-list?22 'let _exp35))))
                          (let ((_let->bindings36 (lambda (_exp37) (_cadr4 _exp37))))
                            (let ((_let->exp38 (lambda (_exp39) (_caddr8 _exp39))))
                              (let ((_letrec1?40 (lambda (_exp41)
                                                   (let ((_p176 (_tagged-list?22 'letrec _exp41)))
                                                     (if _p176
                                                         (let ((_p177 (_cadr4 _exp41)))
                                                           (let ((_p178 (length _p177)))
                                                             (= _p178 1)))
                                                         #f)))))
                                (let ((_letrec1->binding42 (lambda (_exp43) (_caadr6 _exp43))))
                                  (let ((_letrec1->exp44 (lambda (_exp45) (_caddr8 _exp45))))
                                    (let ((_lambda?46 (lambda (_exp47) (_tagged-list?22 'lambda _exp47))))
                                      (let ((_lambda->formals48 (lambda (_exp49) (_cadr4 _exp49))))
                                        (let ((_lambda->exp50 (lambda (_exp51) (_caddr8 _exp51))))
                                          (let ((_if?52 (lambda (_exp53) (_tagged-list?22 'if _exp53))))
                                            (let ((_if->condition54 (lambda (_exp55) (_cadr4 _exp55))))
                                              (let ((_if->then56 (lambda (_exp57) (_caddr8 _exp57))))
                                                (let ((_if->else58 (lambda (_exp59) (_cadddr10 _exp59))))
                                                  (let ((_app?60 (lambda (_exp61) (pair? _exp61))))
                                                    (let ((_app->fun62 (lambda (_exp63) (car _exp63))))
                                                      (let ((_app->args64 (lambda (_exp65) (cdr _exp65))))
                                                        (let ((_prim?66 (lambda (_exp67)
                                                                          (let ((__t068 (eq? _exp67 '+)))
                                                                            (if __t068
                                                                                __t068
                                                                                (let ((__t169 (eq? _exp67 '-)))
                                                                                  (if __t169
                                                                                      __t169
                                                                                      (let ((__t270 (eq? _exp67 '*)))
                                                                                        (if __t270
                                                                                            __t270
                                                                                            (let ((__t371 (eq? _exp67 '=)))
                                                                                              (if __t371
                                                                                                  __t371
                                                                                                  (eq? _exp67 'display))))))))))))
                                                          (let ((_begin?72 (lambda (_exp73) (_tagged-list?22 'begin _exp73))))
                                                            (let ((_begin->exps74 (lambda (_exp75) (cdr _exp75))))
                                                              (let ((_set!?76 (lambda (_exp77) (_tagged-list?22 'set! _exp77))))
                                                                (let ((_set!-var78 (lambda (_exp79) (_cadr4 _exp79))))
                                                                  (let ((_set!-exp80 (lambda (_exp81) (_caddr8 _exp81))))
                                                                    (let ((_let=>lambda82 (lambda (_exp83) (let ((_p179 (_let?34 _exp83)))
                                                                                                             (if _p179
                                                                                                                 (let ((_p180 (_let->bindings36 _exp83)))
                                                                                                                   (let ((_vars84 (_map12 (lambda (xx) (car xx)) _p180)))
                                                                                                                     (let ((_p181 (_let->bindings36 _exp83)))
                                                                                                                       (let ((_args85 (_map12 _cadr4 _p181)))
                                                                                                                         (let ((_p182 (_let->exp38 _exp83)))
                                                                                                                           (let ((_p183 (cons _p182 '())))
                                                                                                                             (let ((_p184 (cons _vars84 _p183)))
                                                                                                                               (let ((_p185 (cons 'lambda _p184)))
                                                                                                                                 (cons _p185 _args85))))))))) _exp83)))))
                                                                      (let ((_arity86 (lambda (_lam87)
                                                                                        (let ((_p186 (_lambda->formals48 _lam87))) (length _p186)))))
                                                                        (letrec ((_xargs88 (lambda (_n89)
                                                                                             (let ((_p187 (<= _n89 0)))
                                                                                               (if _p187
                                                                                                   '()
                                                                                                   (let ((_p188 (number->string _n89)))
                                                                                                     (let ((_p189 (string-append "x" _p188)))
                                                                                                       (let ((_p190 (string->symbol _p189)))
                                                                                                         (let ((_p191 (- _n89 1)))
                                                                                                           (let ((_p192 (_xargs88 _p191)))
                                                                                                             (cons _p190 _p192)))))))))))
                                                                          (let ((_Yn90 (lambda (_n91)
                                                                                         (let ((_p193 (cons 'h '())))
                                                                                           (let ((_p194 (cons 'F '())))
                                                                                             (let ((_p195 (_xargs88 _n91)))
                                                                                               (let ((_p196 (cons 'h '())))
                                                                                                 (let ((_p197 (cons 'h _p196)))
                                                                                                   (let ((_p198 (cons 'F '())))
                                                                                                     (let ((_p199 (cons _p197 _p198)))
                                                                                                       (let ((_p200 (_xargs88 _n91)))
                                                                                                         (let ((_p201 (cons _p199 _p200)))
                                                                                                           (let ((_p202 (cons _p201 '())))
                                                                                                             (let ((_p203 (cons _p195 _p202)))
                                                                                                               (let ((_p204 (cons 'lambda _p203)))
                                                                                                                 (let ((_p205 (cons _p204 '())))
                                                                                                                   (let ((_p206 (cons 'F _p205)))
                                                                                                                     (let ((_p207 (cons _p206 '())))
                                                                                                                       (let ((_p208 (cons _p194 _p207)))
                                                                                                                         (let ((_p209 (cons 'lambda _p208)))
                                                                                                                           (let ((_p210 (cons _p209 '())))
                                                                                                                             (let ((_p211 (cons _p193 _p210)))
                                                                                                                               (let ((_p212 (cons 'lambda _p211)))
                                                                                                                                 (let ((_p213 (cons 'h '())))
                                                                                                                                   (let ((_p214 (cons 'F '())))
                                                                                                                                     (let ((_p215 (_xargs88 _n91)))
                                                                                                                                       (let ((_p216 (cons 'h '())))
                                                                                                                                         (let ((_p217 (cons 'h _p216)))
                                                                                                                                           (let ((_p218 (cons 'F '())))
                                                                                                                                             (let ((_p219 (cons _p217 _p218)))
                                                                                                                                               (let ((_p220 (_xargs88 _n91)))
                                                                                                                                                 (let ((_p221 (cons _p219 _p220)))
                                                                                                                                                   (let ((_p222 (cons _p221 '())))
                                                                                                                                                     (let ((_p223 (cons _p215 _p222)))
                                                                                                                                                       (let ((_p224 (cons 'lambda _p223)))
                                                                                                                                                         (let ((_p225 (cons _p224 '())))
                                                                                                                                                           (let ((_p226 (cons 'F _p225)))
                                                                                                                                                             (let ((_p227 (cons _p226 '())))
                                                                                                                                                               (let ((_p228 (cons _p214 _p227)))
                                                                                                                                                                 (let ((_p229 (cons 'lambda _p228)))
                                                                                                                                                                   (let ((_p230 (cons _p229 '())))
                                                                                                                                                                     (let ((_p231 (cons _p213 _p230)))
                                                                                                                                                                       (let ((_p232 (cons 'lambda _p231)))
                                                                                                                                                                         (let ((_p233 (cons _p232 '())))
                                                                                                                                                                           (cons _p212 _p233)))))))))))))))))))))))))))))))))))))))))))))
                                                                            (let ((_letrec1=>Y92 (lambda (_exp93)
                                                                                                   (let ((_p234 (_letrec1?40 _exp93)))
                                                                                                     (if _p234
                                                                                                         (let ((_binding94 (_letrec1->binding42 _exp93)))
                                                                                                           (let ((_name95 (car _binding94)))
                                                                                                             (let ((_arg96 (_cadr4 _binding94)))
                                                                                                               (let ((_num-args97 (_arity86 _arg96)))
                                                                                                                 (let ((_p235 (_Yn90 _num-args97)))
                                                                                                                   (let ((_p236 (cons _name95 '())))
                                                                                                                     (let ((_p237 (cons _arg96 '())))
                                                                                                                       (let ((_p238 (cons _p236 _p237)))
                                                                                                                         (let ((_p239 (cons 'lambda _p238)))
                                                                                                                           (let ((_p240 (cons _p239 '())))
                                                                                                                             (let ((_p241 (cons _p235 _p240)))
                                                                                                                               (let ((_p242 (cons _p241 '())))
                                                                                                                                 (let ((_p243 (cons _name95 _p242)))
                                                                                                                                   (let ((_p244 (cons _p243 '())))
                                                                                                                                     (let ((_p245 (_letrec1->exp44 _exp93)))
                                                                                                                                       (let ((_p246 (cons _p245 '())))
                                                                                                                                         (let ((_p247 (cons _p244 _p246)))
                                                                                                                                           (cons 'let _p247)))))))))))))))))) _exp93)))))
                                                                              (let ((_singlet?98 (lambda (_l99)
                                                                                                   (let ((_p248 (list? _l99)))
                                                                                                     (if _p248
                                                                                                         (let ((_p249 (length _l99)))
                                                                                                           (= _p249 1)) #f)))))
                                                                                (letrec ((_dummy-bind100 (lambda (_exps101)
                                                                                                           (let ((_p250 (_singlet?98 _exps101)))
                                                                                                             (if _p250
                                                                                                                 (car _exps101)
                                                                                                                 (let ((_p251 (pair? _exps101)))
                                                                                                                   (if _p251
                                                                                                                       (let ((_p252 (car _exps101)))
                                                                                                                         (let ((_p253 (cons _p252 '())))
                                                                                                                           (let ((_p254 (cons '$_ _p253)))
                                                                                                                             (let ((_p255 (cons _p254 '())))
                                                                                                                               (let ((_p256 (cdr _exps101)))
                                                                                                                                 (let ((_p257 (_dummy-bind100 _p256)))
                                                                                                                                   (let ((_p258 (cons _p257 '())))
                                                                                                                                     (let ((_p259 (cons _p255 _p258)))
                                                                                                                                       (cons 'let _p259)))))))))
                                                                                                                       (error "no match"))))))))
                                                                                  (let ((_begin=>let102 (lambda (_exp103)
                                                                                                          (let ((_p260 (_begin->exps74 _exp103)))
                                                                                                            (_dummy-bind100 _p260)))))
                                                                                    (let ((_mutable-variables104 '()))
                                                                                      (let ((_mark-mutable105 (lambda (_symbol106)
                                                                                                                (let ((_p261 (cons _symbol106 _mutable-variables104)))
                                                                                                                  (set! _mutable-variables104 _p261)))))
                                                                                        (letrec ((_is-in?107 (lambda (_S108 _symbol109)
                                                                                                               (let ((_p262 (pair? _S108)))
                                                                                                                 (let ((_p263 (not _p262)))
                                                                                                                   (if _p263
                                                                                                                       #f
                                                                                                                       (let ((_p264 (car _S108)))
                                                                                                                         (let ((_p265 (eq? _p264 _symbol109)))
                                                                                                                           (if _p265
                                                                                                                               #t
                                                                                                                               (let ((_p266 (cdr _S108)))
                                                                                                                                 (_is-in?107 _p266 _symbol109)))))))))))
                                                                                          (let ((_is-mutable?110 (lambda (_symbol111)
                                                                                                                   (_is-in?107 _mutable-variables104 _symbol111))))
                                                                                            (letrec ((_analyze-mutable-variables112 (lambda (_exp113)
                                                                                                                                      (let ((_p267 (_const?30 _exp113)))
                                                                                                                                        (if _p267
                                                                                                                                            #f
                                                                                                                                            (let ((_p268 (_ref?32 _exp113)))
                                                                                                                                              (if _p268
                                                                                                                                                  #f
                                                                                                                                                  (let ((_p269 (_prim?66 _exp113)))
                                                                                                                                                    (if _p269
                                                                                                                                                        #f (let ((_p270 (_lambda?46 _exp113)))
                                                                                                                                                             (if _p270
                                                                                                                                                                 (let ((_p271 (_lambda->exp50 _exp113)))
                                                                                                                                                                   (_analyze-mutable-variables112 _p271))
                                                                                                                                                                 (let ((_p272 (_let?34 _exp113)))
                                                                                                                                                                   (if _p272
                                                                                                                                                                       (let ((_p273 (_let->bindings36 _exp113)))
                                                                                                                                                                         (let ((_p274 (_map12 _cadr4 _p273)))
                                                                                                                                                                           (let ((_$275 (_map12 _analyze-mutable-variables112 _p274)))
                                                                                                                                                                             (let ((_p276 (_let->exp38 _exp113)))
                                                                                                                                                                               (_analyze-mutable-variables112 _p276)))))
                                                                                                                                                                       (let ((_p277 (_letrec1?40 _exp113)))
                                                                                                                                                                         (if _p277
                                                                                                                                                                             (let ((_p278 (_letrec1->binding42 _exp113)))
                                                                                                                                                                               (let ((_p279 (_cadr4 _p278)))
                                                                                                                                                                                 (let ((_$280 (_analyze-mutable-variables112 _p279)))
                                                                                                                                                                                   (let ((_p281 (_letrec1->exp44 _exp113)))
                                                                                                                                                                                     (_analyze-mutable-variables112 _p281)))))
                                                                                                                                                                             (let ((_p282 (_set!?76 _exp113)))
                                                                                                                                                                               (if _p282
                                                                                                                                                                                   (let ((_p283 (_set!-var78 _exp113)))
                                                                                                                                                                                     (_mark-mutable105 _p283))
                                                                                                                                                                                   (let ((_p284 (_if?52 _exp113)))
                                                                                                                                                                                     (if _p284
                                                                                                                                                                                         (let ((_p285 (_if->condition54 _exp113)))
                                                                                                                                                                                           (let ((_$286 (_analyze-mutable-variables112 _p285)))
                                                                                                                                                                                             (let ((_p287 (_if->then56 _exp113)))
                                                                                                                                                                                               (let ((_$288 (_analyze-mutable-variables112 _p287)))
                                                                                                                                                                                                 (let ((_p289 (_if->else58 _exp113)))
                                                                                                                                                                                                   (_analyze-mutable-variables112 _p289))))))
                                                                                                                                                                                         (let ((_p290 (_begin?72 _exp113)))
                                                                                                                                                                                           (if _p290
                                                                                                                                                                                               (let ((_p291 (_begin->exps74 _exp113)))
                                                                                                                                                                                                 (let ((_$292 (_map12 _analyze-mutable-variables112 _p291))) #f))
                                                                                                                                                                                               (let ((_p293 (_app?60 _exp113)))
                                                                                                                                                                                                 (if _p293
                                                                                                                                                                                                     (let ((_$294 (_map12 _analyze-mutable-variables112 _exp113)))
                                                                                                                                                                                                       #f)
                                                                                                                                                                                                     (error "unknown expression type: " _exp113))))))))))))))))))))))))
                                                                                              (letrec ((_m114 (lambda (_chars115)
                                                                                                                (let ((_p295 (null? _chars115)))
                                                                                                                  (if _p295
                                                                                                                      '()
                                                                                                                      (let ((_p296 (car _chars115)))
                                                                                                                        (let ((_p297 (cdr _chars115)))
                                                                                                                          (let ((_p298 (_m114 _p297)))
                                                                                                                            (cons _p296 _p298)))))))))
                                                                                                (let ((_mangle116 (lambda (_symbol117) (let ((_p299 (symbol->string _symbol117)))
                                                                                                                                         (let ((_p300 (_string->list18 _p299)))
                                                                                                                                           (let ((_p301 (_m114 _p300))) (list->string _p301)))))))
                                                                                                  (let ((_java-compile-const118 (lambda (_exp119)
                                                                                                                                  (let ((_p302 (integer? _exp119)))
                                                                                                                                    (if _p302
                                                                                                                                        (let ((_p303 (number->string _exp119)))
                                                                                                                                          (string-append "new IntValue(" _p303 ")"))
                                                                                                                                        (error "unknown constant: " _exp119))))))
                                                                                                    (let ((_java-compile-prim120 (lambda (_p121)
                                                                                                                                   (let ((_p304 (eq? '+ _p121)))
                                                                                                                                     (if _p304
                                                                                                                                         "sum"
                                                                                                                                         (let ((_p305 (eq? '- _p121)))
                                                                                                                                           (if _p305 "difference"
                                                                                                                                               (let ((_p306 (eq? '* _p121)))
                                                                                                                                                 (if _p306
                                                                                                                                                     "product"
                                                                                                                                                     (let ((_p307 (eq? '= _p121)))
                                                                                                                                                       (if _p307
                                                                                                                                                           "numEqual"
                                                                                                                                                           (let ((_p308 (eq? 'display _p121)))
                                                                                                                                                             (if _p308
                                                                                                                                                                 "display"
                                                                                                                                                                 (error "unhandled primitive " _p121))))))))))))))
                                                                                                      (let ((_java-compile-ref122 (lambda (_exp123)
                                                                                                                                    (let ((_p309 (_is-mutable?110 _exp123)))
                                                                                                                                      (if _p309
                                                                                                                                          (let ((_p310 (_mangle116 _exp123)))
                                                                                                                                            (string-append "m_" _p310 ".value"))
                                                                                                                                          (_mangle116 _exp123))))))
                                                                                                        (letrec ((_java-compile-formals124 (lambda (_formals125)
                                                                                                                                             (let ((_p311 (pair? _formals125)))
                                                                                                                                               (let ((_p312 (not _p311)))
                                                                                                                                                 (if _p312
                                                                                                                                                     ""
                                                                                                                                                     (let ((_p313 (car _formals125)))
                                                                                                                                                       (let ((_p314 (_mangle116 _p313)))
                                                                                                                                                         (let ((_p315 (cdr _formals125)))
                                                                                                                                                           (let ((_p316 (pair? _p315)))
                                                                                                                                                             (let ((_p319 (if _p316
                                                                                                                                                                              (let ((_p317 (cdr _formals125)))
                                                                                                                                                                                (let ((_p318 (_java-compile-formals124 _p317)))
                                                                                                                                                                                  (string-append ", " _p318)))
                                                                                                                                                                              "")))
                                                                                                                                                               (string-append "final Value " _p314 _p319))))))))))))
                                                                                                          (letrec ((_java-wrap-mutables126 (lambda (_vars127)
                                                                                                                                             (let ((_p320 (pair? _vars127)))
                                                                                                                                               (let ((_p321 (not _p320)))
                                                                                                                                                 (if _p321
                                                                                                                                                     ""
                                                                                                                                                     (let ((_p322 (car _vars127)))
                                                                                                                                                       (let ((_p323 (_is-mutable?110 _p322)))
                                                                                                                                                         (let ((_p328 (if _p323
                                                                                                                                                                          (let ((_p324 (car _vars127)))
                                                                                                                                                                            (let ((_p325 (_mangle116 _p324)))
                                                                                                                                                                              (let ((_p326 (car _vars127)))
                                                                                                                                                                                (let ((_p327 (_mangle116 _p326)))
                                                                                                                                                                                  (string-append " final ValueCell m_" _p325 " = new ValueCell(" _p327 ");n")))))
                                                                                                                                                                          "")))
                                                                                                                                                           (let ((_p329 (cdr _vars127)))
                                                                                                                                                             (let ((_p330 (_java-wrap-mutables126 _p329)))
                                                                                                                                                               (string-append _p328 _p330))))))))))))
                                                                                                            (let ((_java-compile-lambda128 #f))
                                                                                                              (let ((_java-compile-args129 #f))
                                                                                                                (let ((_java-compile-set!130 #f))
                                                                                                                  (let ((_java-compile-app131 #f))
                                                                                                                    (let ((_java-compile-if132 #f))
                                                                                                                      (letrec ((_java-compile-exp133 (lambda (_exp134)
                                                                                                                                                       (let ((_p331 (_const?30 _exp134)))
                                                                                                                                                         (if _p331
                                                                                                                                                             (_java-compile-const118 _exp134)
                                                                                                                                                             (let ((_p332 (_prim?66 _exp134)))
                                                                                                                                                               (if _p332
                                                                                                                                                                   (_java-compile-prim120 _exp134)
                                                                                                                                                                   (let ((_p333 (_ref?32 _exp134)))
                                                                                                                                                                     (if _p333
                                                                                                                                                                         (_java-compile-ref122 _exp134)
                                                                                                                                                                         (let ((_p334 (_lambda?46 _exp134)))
                                                                                                                                                                           (if _p334
                                                                                                                                                                               (_java-compile-lambda128 _exp134)
                                                                                                                                                                               (let ((_p335 (_if?52 _exp134)))
                                                                                                                                                                                 (if _p335
                                                                                                                                                                                     (_java-compile-if132 _exp134)
                                                                                                                                                                                     (let ((_p336 (_set!?76 _exp134)))
                                                                                                                                                                                       (if _p336
                                                                                                                                                                                           (_java-compile-set!130 _exp134)
                                                                                                                                                                                           (let ((_p337 (_let?34 _exp134)))
                                                                                                                                                                                             (if _p337
                                                                                                                                                                                                 (let ((_p338 (_let=>lambda82 _exp134)))
                                                                                                                                                                                                   (_java-compile-exp133 _p338))
                                                                                                                                                                                                 (let ((_p339 (_letrec1?40 _exp134)))
                                                                                                                                                                                                   (if _p339
                                                                                                                                                                                                       (let ((_p340 (_letrec1=>Y92 _exp134)))
                                                                                                                                                                                                         (_java-compile-exp133 _p340))
                                                                                                                                                                                                       (let ((_p341 (_begin?72 _exp134)))
                                                                                                                                                                                                         (if _p341
                                                                                                                                                                                                             (let ((_p342 (_begin=>let102 _exp134)))
                                                                                                                                                                                                               (_java-compile-exp133 _p342))
                                                                                                                                                                                                             (let ((_p343 (_app?60 _exp134)))
                                                                                                                                                                                                               (if _p343
                                                                                                                                                                                                                   (_java-compile-app131 _exp134)
                                                                                                                                                                                                                   (error "no match"))))))))))))))))))))))))
                                                                                                                        (let ((_$349 (set! _java-compile-lambda128 (lambda (_exp135)
                                                                                                                                                                     (let ((_formals136 (_lambda->formals48 _exp135)))
                                                                                                                                                                       (let ((_num-args137 (length _formals136)))
                                                                                                                                                                         (let ((_p344 (number->string _num-args137)))
                                                                                                                                                                           (let ((_p345 (_java-compile-formals124 _formals136)))
                                                                                                                                                                             (let ((_p346 (_java-wrap-mutables126 _formals136)))
                                                                                                                                                                               (let ((_p347 (_lambda->exp50 _exp135)))
                                                                                                                                                                                 (let ((_p348 (_java-compile-exp133 _p347)))
                                                                                                                                                                                   (string-append "new NullProcValue" _p344 " () {n" " public Value apply(" _p345 ") {n" _p346 "n" "  return " _p348 " ;n" "}}n"))))))))))))
                                                                                                                          (let ((_$359 (set! _java-compile-args129 (lambda (_args138)
                                                                                                                                                                     (let ((_p350 (pair? _args138)))
                                                                                                                                                                       (let ((_p351 (not _p350)))
                                                                                                                                                                         (if _p351
                                                                                                                                                                             ""
                                                                                                                                                                             (let ((_p352 (car _args138)))
                                                                                                                                                                               (let ((_p353 (_java-compile-exp133 _p352)))
                                                                                                                                                                                 (let ((_p354 (cdr _args138)))
                                                                                                                                                                                   (let ((_p355 (pair? _p354)))
                                                                                                                                                                                     (let ((_p358 (if _p355
                                                                                                                                                                                                      (let ((_p356 (cdr _args138)))
                                                                                                                                                                                                        (let ((_p357 (_java-compile-args129 _p356)))
                                                                                                                                                                                                          (string-append ", " _p357)))
                                                                                                                                                                                                      "")))
                                                                                                                                                                                       (string-append _p353 _p358)))))))))))))
                                                                                                                            (let ((_$364 (set! _java-compile-set!130 (lambda (_exp139)
                                                                                                                                                                       (let ((_p360 (_set!-var78 _exp139)))
                                                                                                                                                                         (let ((_p361 (_mangle116 _p360)))
                                                                                                                                                                           (let ((_p362 (_set!-exp80 _exp139)))
                                                                                                                                                                             (let ((_p363 (_java-compile-exp133 _p362)))
                                                                                                                                                                               (string-append "VoidValue.Void(m_" _p361 ".value = " _p363 ")")))))))))
                                                                                                                              (let ((_$368 (set! _java-compile-app131 (lambda (_exp140)
                                                                                                                                                                        (let ((_args141 (_app->args64 _exp140)))
                                                                                                                                                                          (let ((_fun142 (_app->fun62 _exp140)))
                                                                                                                                                                            (let ((_num-args143 (length _args141)))
                                                                                                                                                                              (let ((_p365 (number->string _num-args143)))
                                                                                                                                                                                (let ((_p366 (_java-compile-exp133 _fun142)))
                                                                                                                                                                                  (let ((_p367 (_java-compile-args129 _args141)))
                                                                                                                                                                                    (string-append "((ProcValue" _p365 ")(" _p366 ")).apply(" _p367 ")n")))))))))))
                                                                                                                                (let ((_$375 (set! _java-compile-if132 (lambda (_exp144)
                                                                                                                                                                         (let ((_p369 (_if->condition54 _exp144)))
                                                                                                                                                                           (let ((_p370 (_java-compile-exp133 _p369)))
                                                                                                                                                                             (let ((_p371 (_if->then56 _exp144)))
                                                                                                                                                                               (let ((_p372 (_java-compile-exp133 _p371)))
                                                                                                                                                                                 (let ((_p373 (_if->else58 _exp144)))
                                                                                                                                                                                   (let ((_p374 (_java-compile-exp133 _p373)))
                                                                                                                                                                                     (string-append "(" _p370 ").toBoolean() ? (" _p372 ") : (" _p374 ")")))))))))))
                                                                                                                                  (let ((_java-compile-program145 (lambda (_exp146)
                                                                                                                                                                    (let ((_p376 (_java-compile-exp133 _exp146)))
                                                                                                                                                                      (string-append "public class BOut extends RuntimeEnvironment {n" " public static void main (String[] args) {n" _p376 " ;n" " }n" "}n")))))
                                                                                                                                    (let ((_input-program147 '(let ((x 10)) (letrec ((f (lambda (n) (if n (set! x 3) (begin x n f))))) (f 10)))))
                                                                                                                                      (let ((_$377 (_analyze-mutable-variables112 _input-program147)))
                                                                                                                                        (_java-compile-program145 _input-program147)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))